/* Only User */
create role "user";
create user juliya with password 'qwerty' role "user";
ALTER DEFAULT PRIVILEGES IN SCHEMA w_dir GRANT SELECT ON TABLES TO "user";
ALTER DEFAULT PRIVILEGES IN SCHEMA w_dir GRANT EXECUTE ON FUNCTIONS TO "user";


/* Moderator */
create role moderator;
CREATE USER danya WITH PASSWORD 'jw8s0F4' VALID UNTIL '2023-01-01' role moderator;
ALTER DEFAULT PRIVILEGES IN SCHEMA w_dir GRANT SELECT,INSERT,UPDATE ON TABLES TO moderator;
ALTER DEFAULT PRIVILEGES IN SCHEMA w_dir GRANT EXECUTE ON FUNCTIONS TO moderator;


/* Admin */
create role "admin";
CREATE USER sanya WITH PASSWORD 'aswd' VALID UNTIL '2024-01-01' role "admin";
ALTER DEFAULT PRIVILEGES IN SCHEMA w_dir GRANT SELECT,INSERT,UPDATE,DELETE ON TABLES TO moderator;
ALTER DEFAULT PRIVILEGES IN SCHEMA w_dir GRANT EXECUTE ON FUNCTIONS TO moderator;

